# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1c963276fafe3065b5a4d61727dc60d682ab13735d431e97dafe62b6101d359b941d811398acf9c9e847220376b2d5e8e48dcbe3f6d9bfbfe489a28eff86e3a6

test:
  secret_key_base: 049f064000bfd08b28989f0a775e37e47ab996437053c724c6d2e3f13ad40d9394d26878b96389fc6e3938db317cae5256fff6cb32757c39d25624e31842be20

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
